# 音频配置
ao=coreaudio

# 视频配置
gpu-api=vulkan
macos-render-timer=precise
target-colorspace-hint=yes

[ao-avfoundation]
profile-cond="p['audio-params/channel-count'] > 2"
profile-restore=copy-equal
ao=avfoundation
