name: Pack
on: [push, pull_request]
jobs:
  pack-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
      - name: Install dependencies
        run: sudo apt -y install findutils zip unzip
      - name: Pack to zip
        run: |
          cd "$GITHUB_WORKSPACE"
          echo $(($(git log -1 --format=%ct) * 1000)) > .commit_time
          cd ..
          zip -9 -r -v "$RUNNER_TEMP/mpv-config".zip mpv-config
          zip -d -v "$RUNNER_TEMP/mpv-config.zip" \*.git\* mpv-config/git-modules\*
          unzip -d "$RUNNER_TEMP" "$RUNNER_TEMP/mpv-config.zip"
      - name: Create clean script
        run: |
          cd "$RUNNER_TEMP/mpv-config"
          echo 'CD %~dp0' > clean.bat
          find . -type f ! -path ./clean.bat | sed -e 's|^./|DEL |g' -e 's|/|\\|g' >> clean.bat
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: mpv-config
          path: ${{ runner.temp }}/mpv-config
